reverting most

diff --git a/.github/actions/cache-query-compilation/action.yml b/.github/actions/cache-query-compilation/action.yml
--- a/.github/actions/cache-query-compilation/action.yml
+++ b/.github/actions/cache-query-compilation/action.yml
@@ -44,17 +44,18 @@ runs:
         restore-keys: | # restore from another random commit, to speed up compilation.
           codeql-compile-${{ inputs.key }}-${{ github.ref_name }}- 
           codeql-compile-${{ inputs.key }}-main-
-    - uses: actions/setup-node@v3
     - name: Fill compilation cache directory
       id: fill-compilation-dir
       shell: bash 
       run: |
         # Move all the existing cache into another folder, so we only preserve the cache for the current queries.
-        node $GITHUB_WORKSPACE/.github/actions/cache-query-compilation/move-caches.js ${COMBINED_CACHE_DIR}
+        mkdir -p ${COMBINED_CACHE_DIR}
+        rm -f **/.cache/{lock,size} # -f to avoid errors if the cache is empty.
+        # copy the contents of the .cache folders into the combined cache folder.
+        cp -r **/.cache/* ${COMBINED_CACHE_DIR}/ || : # ignore missing files
+        # clean up the .cache folders
+        rm -rf **/.cache/*
 
         echo "compdir=${COMBINED_CACHE_DIR}" >> $GITHUB_OUTPUT
-
-        du -sh ${COMBINED_CACHE_DIR} # print the size of the cache.
-        find ${COMBINED_CACHE_DIR} -type f # print the files in the cache.
       env: 
         COMBINED_CACHE_DIR: ${{ runner.temp }}/compilation-dir
